batch_size: 1024
block_train_epochs: 500
concurvity_threshold: 0.5
decay_rate: 0.995
eta_prune: 0.01
finetune_epochs: 500
hidden_sizes:
- 64
- 32
inter_hidden: []
inter_units: 32
num_epochs: 500
num_units: 64
patience: 25
seed: 42
task: classification
test_frac: 0.2
top_m: 10
val_check_interval: 10
val_frac: 0.1
activation: relu
dropout: 0.05
feature_dropout: 0
l2_regularization: 3.3525493450935374e-05
lr: 0.027238818000585665
output_regularization: 0.012246530332089871
clarity_regularization: 0.0
