dataset_path: C:\Users\maart\OneDrive\Documenten\Universiteit\Scriptie\python_repo\thesis-nam\datasets\raw\compas-scores-two-years.csv
num_units: 64
hidden_sizes:
- 64
- 32
decay_rate: 0.995
batch_size: 1024
num_epochs: 250
patience: 50
val_check_interval: 10
task: classification
val_frac: 0.15
test_frac: 0.15
seed: 42
activation: relu
lr: 0.007704545276127354
output_regularization: 0.023166281131917488
l2_regularization: 9.927916301446926e-05
dropout: 0
feature_dropout: 0.2
