dataset_path: C:\Users\maart\OneDrive\Documenten\Universiteit\Scriptie\python_repo\thesis-nam\datasets\raw\compas-scores-two-years.csv
num_units: 64
hidden_sizes:
- 64
- 32
inter_units: 32
inter_hidden: []
decay_rate: 0.995
batch_size: 1024
num_epochs: 100
patience: 50
val_check_interval: 10
task: classification
val_frac: 0.1
test_frac: 0.2
seed: 42
top_m: 10
eta_prune: 0.01
block_train_epochs: 100
finetune_epochs: 100
concurvity_threshold: 0.5
activation: relu
lr: 0.07091204515690985
output_regularization: 0.009917141850481218
l2_regularization: 1.8179112450156835e-05
dropout: 0.05
feature_dropout: 0.05
clarity_regularization: 0.011751562394003595
