# COMPAS baseline
dataset_path: C:\Users\maart\OneDrive\Documenten\Universiteit\Scriptie\python_repo\thesis-nam\datasets\raw\compas-scores-two-years.csv
num_units: 64
hidden_sizes: [64, 32]
activation: relu
dropout: 0.1
feature_dropout: 0.05

output_regularization: 0.2078
l2_regularization: 0.0

lr: 0.02082
decay_rate: 0.995

batch_size: 1024
num_epochs: 1000
patience: 100
val_check_interval: 10
task: classification

val_frac: 0.15
test_frac: 0.15
seed: 42